#!/bin/bash
## table/qry backup for postgresql
read -r -d '' USAGE << EOM
Usage:
 pg-tbl [options] table|qryfile
 
 Default (no -i option given): backup table data or executes the query
 specified in qryfile. If qryfile is '-' then a query is taken from stdin

 If -i option is given with a file name it attempts to insert
 the content of the file into the named table

 Options:
 Table write/insert mode:
  -i tbl_backup_file  table restore mode: use pg_restore to restore/insert the 
                      table data found in the given file
 Table/query output:
  -f col1,col2..      comma delimited list of columns (fields)
                      to extract from table
  -C                  output is CSV instead of tab delimited
  -H                  include table header (only for -C option)
  -S                  only show table dependencies and exit
  -h/-s server        override PGHOST with this server name
  -p port             overrides default port
  -b/-d database      override PGDATABASE
  -U/-u               override PGUSER
 
 Note: this utility relies on pg_dump, pg_restore & psql utilties 
 and ~/.pgpass must be configured for user authentication.
EOM
#TODO:
# -I/-A               for -i, load into a temporary table and insert/append
#                     only the missing rows into the target table

trunc=""
server=""
db=""
user=""
pgopts=""
csv=""
dump=""
infile=""
hdr=""
showdeps=""
quiet=""
tcols=""

function errout {
 echo -e "Error: $1"
 exit 1
}

function psqlget {
  qry="COPY ($1) TO STDOUT WITH (format 'text')"
  psql $pgopts -c "$qry"
}


if [[ -z "$1" || "$1" == "--help" || ( -z "$2" && "$1" == "-h" ) ]]; then
   echo "$USAGE"
   exit 1
fi

while getopts "s:b:h:d:p:f:u:U:qIAHSCDi:" OPT; do
  case $OPT in
  q)
    quiet=1
    ;;
  S)
    showdeps=1
    ;;
  C)
    csv=1
    ;;
  D) 
    dump=1
    ;;
  H) 
    hdr=1
    ;;
  b | d)
    db="$OPTARG"
    pgopts="$pgopts -b $dbname"
    ;;
  u | U)
    user="$OPTARG"
    pgopts="$pgopts -U $user"
    ;;
  h | s)
    server="$OPTARG"
    pgopts="$pgopts -h $server"
    ;;
  p)
    port="$OPTARG"
    pgopts="$pgopts -p $port"
    ;;
  i)
    infile="$OPTARG"
    if [[ ! -f $infile ]]; then
      errout "File '$infile' not found!"
    fi
    ;;
  f)
    tcols="$OPTARG"
    ;;
  *)
    echo "$USAGE"
    echo "Error: incorrect options provided"
    exit 1
    ;;
   esac
done
#---
shift $((OPTIND-1))
#so now $@ are just the positional arguments
if [[ -z $server ]]; then server=$PGHOST; fi
if [[ -z $db ]]; then db=$PGDATABASE; fi

table="$1" ## could be more than one?

if [[ -z $table ]]; then
 errout "database table or query file not specified!"
fi
if [[ -z $quiet ]]; then
 >&2 echo "Using server '$server', database '$db'"
fi
# checking table/view existence
r=$(psqlget "select exists (select from pg_tables where schemaname='public' AND tablename='$table')")
##"
r=$(echo $r | tr '[:upper:]' '[:lower:]')
if [[ $r == "f" ]]; then
  # try to check if it's a view?
  r=$(psqlget "select exists (select from pg_views where viewname='$table')")
  ##"
  r=$(echo $r | tr '[:upper:]' '[:lower:]')
  if [[ $r == "f" ]]; then
    errout "table/view '$table' does not exist!"
  fi
fi

if [[ -n $showdeps ]]; then
  psqlget "with recursive chain as ( \
    select classid, objid, objsubid, conrelid from pg_depend d \
    join pg_constraint c on c.oid = objid \
    where refobjid = '$table'::regclass and deptype = 'n' \
union all \
    select d.classid, d.objid, d.objsubid, c.conrelid from pg_depend d \
    join pg_constraint c on c.oid = objid \
    join chain on d.refobjid = chain.conrelid and d.deptype = 'n' ) \
select pg_describe_object(classid, objid, objsubid), pg_get_constraintdef(objid) \
from chain" 
  
  exit 0
fi

if [[ -z "$infile" ]]; then # output mode
  ## backup to: table.date.gz
  #date=$(date '+%y_%m_%d-%H:%M')
  date=$(date '+%y_%m_%d')
  fout="$table.$date"
  copyfmt="format 'text'"
  if [[ -n $csv ]]; then
    copyfmt="format 'csv'"
    fout=$fout.csv.gz
    if [[ -n $hdr ]]; then copyfmt="$copyfmt,header true"; fi
  else
    copyfmt="$copyfmt,null ''" 
    fout=$fout.tab.gz
  fi
  if [[ -f "$table" ]]; then # execute query in given file
    psql $pgopts -f "$table"
  else
    qry="copy $table to stdout with ($copyfmt)"    
    if [[ -n $tcols ]]; then
      qry="copy (select $tcols from $table) to stdout with ($copyfmt)"
    fi
    psql $pgopts -c "$qry" 
  fi
  exit 0
fi
## -- importing given file into table
copyfmt="format 'text'"
if [[ -n $csv ]]; then
  copyfmt="format 'csv'"
  if [[ -n $hdr ]]; then copyfmt="$copyfmt,header true"; fi
else
  copyfmt="$copyfmt,null ''" 
fi

qry="\\copy $table from stdin with ($copyfmt)"
if [[ $infile =~ \.t?gz$ ]];
  gzip -cd $infile | psql $pgopts -c "$qry"
else
  psql $pgopts -c "$qry" < $infile
fi

