#!/usr/bin/perl
use strict;
use Getopt::Std;

my $usage = q/Show SLURM usage (occupancy) info by node and CPU usage.
Usage:
  si
    -a : show all partitions, not just shared and bluejay
    -p : show the usage for specified partitions
/;
#  -l : list nodes in the last column
#  -m : show the usage\/occupancy of each partition by memory, not CPUs

umask 0002;
getopts('ap:') || die($usage."\n");
my $me = (lc($ARGV[0])=~m/^[mei1]+$/);
# --


#************ Subroutines **************
#!/usr/bin/perl
use strict;
# Run sinfo command and capture the output
my $parts=$Getopt::Std::opt_p;
if ($parts) {
 $parts='-p'.$parts;
} else {
 $parts='-pshared' unless $Getopt::Std::opt_a;
}
my $cmd='sinfo '.$parts.' -o "%.16P %.10A %.5D  %.16C"';
## A/I/O/T = allocated/idle/other/total 
#$ sinfo -p bluejay,shared  -o "%.16P %.10A %.5D  %.20C"
#     PARTITION   NODES(A/I)  NODES     CPUS(A/I/O/T)
#      shared*       40/1     42       578/1774/48/2400
#      bluejay       7/0       8        104/232/48/384

my $sinfo_output = `$cmd`;
my @pinfo = split("\n", $sinfo_output);
foreach (@pinfo) {
    next if length()<2;
    next if (m/PARTITION/);
    chomp;
    s/^\s+//;s/\s+$//;
    my ($pname, $nu, $tn, $cu) = split(/\s+/); 
    my ($ca, $ci, $co, $ct)=split(/\//, $cu);
    my $usg = sprintf('%d', (100*($ct-$ci))/$ct);
    print("Partition '$pname' has $usg\% CPU usage ($ci CPUs idle out of $ct)\n");
}
